# The politics of NOC internationalization {#paper3}

## Introduction {#intro03}

> **Due to its geographical location and proximity to Russia, Tajikistan is of strategic interest to Russia and, correspondingly, the Gazprom Group.** Gazprom is interested in preserving the stable economic situation in Central Asia in general and Tajikistan in particular. Therefore, Gazprom is both a strategic partner to Tajikistan as well as its largest investor. The Group’s main objective in Tajikistan, besides purely commercial profit, is to guarantee the energy security of the republic, at a time when the country’s economy is experiencing a serious shortage of oil and gas.^[ Gazprom International: Tajikistan (Country Profile). http://www.gazprom-international.com/en/operations/country/tajikistan]

The politics of NOC internationalization is often the most discussed aspect of a particular investment or acqusition. Popular observers and concerned politicians regularly argue that a particular deal is politically motivated or comes with political strings attached.^[ For example, see the discussion int the popular press surrounding CNOOC's potential acquisition of UNOCAL. **example cite needed**.] A 2007 Congressional Report on NOCs listed foreign policy as a core objective: "National oil companies can also be used by their national governments as a tool to achieve foreign policy goals, leading to direct alliances as well as [firm to firm] ties that can pave the way to political relationships. Oil is a strategic commodity in the world economy, and its production and use can foster strategic relationships." [@pirog_role_2007, 7-8]. 

Statements made by the investing firm or state that confirm this --- like the one above, found on a public Gazprom website --- are harder to come by. It seems obvious that the activities engaged in by a state's largest economic entity will necessarily have political implications and impacts, but getting an empirical handle on those implications and impacts is difficult. Justifications for a particular investment decision or location choice can always be made by appealing to a purely commercial logic; the relationships woven between political actors through a web of commercial/contractual relationships are almost necessarily subtle and subtextual rather than explicit or codified. As such, research into the political implications of the commercial relationships formed when national oil companies (NOCs) build out an international network are few in number and limited in scope. 

At the same time, however, the topic is highly deserving of more rigorous empirical attention. In many cases, a state's national oil company is the crown jewel of the state's economic and social apparatus. It stands to reason that political owners may be highly invested in the international activity of their firms for both commercial and political reasons. Acquisitions and investments open doors that diplomats are involved in both creating and leveraging once in place. There is a reason that the highest level of political dignitary have been involved in the announcement and opening of many China's most significant investments in Africa.^[ **TODO: insert China Africa cite here**.] When it comes to international expansion, the state-firm relationship can be mutually beneficial. As the chair of an Indian NOC states, "diplomatic support is very, very crucial as we search for assets overseas."^[ @kakatey_india_2010, quoted in @meckling_oil_2015, 1180.] 

This chapter addresses the political implications of NOC internationalization in three moves. First, we make 'political implications' specific by enumerating several of the most important ways that NOC internationalization can have aspects and implications beyond the purely commercial. We group these into a typology of political internationalization, and group each component into home state, host state, and firm-specific categories. We substantiate these implications with sailient anecdotes. Our objective with this section is to be as specific and explict as possible about the the potential shape of the political in the context of NOC internationalization.

Second, we describe and investigate the web of state-to-state relationships that emerge from internationalization activities of NOCs across the globe. We argue that subsidiary networks emerge in measurably distinct forms: these networks can be used to distinguish NOCs from IOCs, but also to distinguish between different kinds of NOCs. **TODO: More detail on this one here.**

Third, we attempt to gain leverage over the causal effect of NOC internationalization by examining key internationalization events and their impacts over time. Our approach combines careful attention to causal inference in the context of time-varying outcomes with statistical techniques --- specifically, diffusion-regression state-space modeling --- designed to gain leverage over the causal impact of a treatment over time in both experimental and observational settings. 

## Motivation: The Politics of Internationalization {#motiv03} 

What does it mean to say that the international activity of NOCs has political implications? The objective of this section is to articulate some of these implications in a manner that leaves them more conducive to empirical investigation. The discussion below pursues one specific way of conceptualizing these implitcations: it makes the case that **NOC internationalization is political insofar as it generates (or is expected to generate) political outcomes for the parent state**. These political outcomes include (but are likely not limited to) improved state-to-state relationships, amplified international signalling, and strengthened international trade flows.

While this section pursues a focus on the international political implications of NOC internationalization for the parent state of a NOC, there are at least three other approaches deserving of further inquiry. First, NOC internationalization has political implications for the state receiving the investment or expansion activity. In some ways this is a corollary of the main thread pursued here, but it also offers significant departures. Sanctioning NOC internationalization activity by approving specific projects can have important political implications whether or not the parent state is engaged in or attentive to the firm acitvity at all. In many cases regulators grapple with the percieved costs and benefits of allowing a state-owned firm to develop operations, and in some cases the political or regulatory pushback has been significant enough to derail the efforts entirely (eg. Unocal in the United States, **more detail or footnote here**). 

Second, there are political implications of international activity for NOCs themselves. They may actively leverage their political connections to open channels of access or communication, may find their commercial efforts inhibited by the political reputation of their home state, or may utilize their political backing to justify and pursue more risk-acceptant investments. 

Third, international activity engaged in by NOCs likely also has implications for the parent state in the domestic sphere. Firms that grow internationally may build out more robust and valuable domestic infrastructure, changing the way the state may be able to use the proceeds or instittusions of the firm to support the domestic economy and engage in patronage of various forms.

While individually compelling, we do not pursue any of these in further theoretical or empirical detail here. We revisit them both in the discussion section that concludes these chapters, and flesh them out as some of the most promising avenues for further research into this topic. This section, and the analysis that follows, is limited in scope to the international political implications of NOC internationalization. 

### The intrinsic political importance of commercial activity

NOC internationalization has political implications when the state derives or expects political benefit from the NOCs performance in general, and its performance linked to investments and expansions made in particular. In this way, the purely commercial outcomes of firm activity abroad can have important political outcomes: these outcomes can help a government shore up support domestically, fund key initiatives, and engage in other politically-motivated activities. The most basic (but significant) way this operates is in NOC contributions to state treasuries: many states use their NOC profit to fund the state, and in many cases the NOC is the largest single contributor of funds. Growth in these contributions --- either because of rising oil prices, improved firm performance, or both --- plays an important role in improving the political fortunes of the elites or parties in power. State interest in the commercial outcomes delivered by their NOC's international activity goes the other way as well. International expansion is never risk free, and the state may pay a political price for poor investments or a suffering firm. Just as the state may benefit from rising contributions, shortfalls can create difficulties vis-a-vis the electorate (or selectorate).

Recent events in Venezuela illustrate how international subdidiaries can be both political *assets* and *liabilities*. In spring 2019 the Venezuelan government approved a controversial measure to pay overdue interest payments against the country's only remaining non-defaulted bond, PDVSA 2020 debt. This measure is going ahead, despite the desperate general state of Venezuela's finances and economy, because non-payment would open one of PEMEX's most important assets to seizure by creditors. The PEMEX 2020 bond is backed by shares in Citgo, a US refiner: its loss is a bridge too far for the Venezuelan government [@armas_venezuela_2019; @smith_venezuela_2019]. Citgo is one of PEMEX's largest and most productive international subsidiaries. The Venezuelan government is willing to risk significant public outcry and balance-sheet pain in other areas of its economy to secure this valuable international asset.

Evaluating the proposition that NOC internationalization can be political by virtue of how political actors view and understand its commercial dimensions presents significant challenges. It is likely that at some level, *all* deals of this nature --- ie. pursued by a state-owned entity --- likely hold at least some level of political importance for the parties involved; many non-state-owned transactions do as well. Assessing the strength or saliency of this importance from case to case is extremely difficult, and require far more nuanced data regarding the perceptions and preferences of state and firm actors than are currently available.

### NOC internationalization and bilateral politics

In what ways might the international activity of NOCs generate political outcomes for their parent states, beyond the intrisic political importance of large-scale commercial transactions? First, firm activity in other countries might impact the state-to-state relationships between that country and the NOC's parent state. Firm investments are rarely made with diplomatic or strategic strings explicitly attached, but it is likely that at least in some cases, commercial deals are expected to deliver political or diplomatic value as well. This could mean that the state receiving the investment is more likely to participate in bilateral or multilateral projects, act as a regional partner for the investing firm's state, or support that state's initiatives in international forums like the United Nations. 

The strong version of this expected impact is that the international link formed by the NOC can be a direct channel of influence or even coercion. The likelihood of this influence being meaningful may be higher when the receiving state becomes dependent on that relationship. In this vein, some observers view Gazprom's near-monoplist position in many European gas markets as constituting a 'gas weapon': the ability of the Russian state to turn off critical supplies at moments of tension may be an important lever or influence over states that require these supplies to run their economies and supply their domestic markets effectively.^[ **Insert citations here.**] Supply chain relationships work in both directions, however: the supplier is often just as reliant on stability of supply, and places a high value on a commercially reliable reputation. Any understanding of a resource 'weapon' must be balanced against the possibility that commercial linkages operate as 'shields': creating an important asset for the investing state that they wouldn't want to risk disrupting by overly antagonistic diplomatic or strategic actions. 

The more likely or common process by which NOC activities abroad impact interstate relations is as one tie among others that link the two states. A firm's investments may facilitate or improve lines of communication, coordination, and cooperation, especially when the firm is large relative to the diplomatic apparatuses of the states in question. 

**Insert appropriate anecdote here: maybe India / Saudi, or China / Africa**

Alternatively, the political implications of commercial relationships formed by NOCs may operate irrespective of the active bilateral relationship between the two states. The state-owner of the investing firm may be interested in supporting the economy or general stability of another state whether or not that state's behaviour changes. The opening quote from Gazprom, situated at the beginning of this chapter, illustrates this implicaiton clearly: Russia's political interest in Gazprom's investment in Tajikistan stems in part at least from an interest in securing the stability of an important neighbour on Russia's volatile southern border. This interest likely adheres irrespective of how Tajikistan responds to Gazprom or Russia's actions. 

These political implications likely adhere to other forms of commercial activity: NOCs aren't the only firms capable of generating political impacts of this nature, especially in a strategically important sector like hydrocarbon extraction and production. Political entities can invested in the activities of non-state-owned firms as well. The condition of state-ownership does create a stronger link between state and firm, however, and so it is plausible that these implications are more substantial in the context of NOC activity than in the context of activity engaged in by other multinational oil and gas companies. 

Within this conceptualization, bilateral relations and firm-to-firm relations are closely bound together. States may sanction and even push firms to expand and develop international connections in ways that improve specific bilateral ties or deliver against specific political objectives. Alternatively, firms may engage in commercial activities that subsequently deliver political benefits (or costs) for the parent state.

### NOC internationalization and international trade

Direct political ties are one form of linkage NOC activity can impact; trade ties are another. States may derive (or expect to derive) material within-sector and cross-sector benefits in the trade of both goods and services as a result of a NOC-subsidiary link being formed. In the most direct sense, NOC-subsidiary linkages enable the intra-firm exchange of goods and services. More broadly, however, the state may reasonably expect knock-on benefits resulting from improved partnerships, enabling agreements or regulatory breakthroughs, or other aspects of the link. These are likely strongest within the sector in question, but may also be felt in adjacent and even very different areas of the economy. 

Illustrations of this connection in practice are readily available. Bilateral trade growth between Russia and the United Arab Emirates, for instance, covers several critical sectors, including but not limited to energy: efforts to strengthen those ties necessarily involve ADNOC CEO and Minister of State Sultan Al Jaber.^["Russia, UAE trade ties on upswing", *Gulf Times*, https://gulfnews.com/business/markets/russia-uae-trade-ties-on-upswing-1.2047901.]

Sometimes trade, politics, and firm activity are so closely linked together as to be inseperable. Consider recently concluded United Arab Emirates - China Economic Forum, held alongside Crown Prince Sheikh Mohamed bin Zayed’s visit to China in the summer of 2019. The forum concluded with the signing of several Memorandums of Understanding across several areas of collaboration: these included MOU's establishing an interest in direct collaboration between NOCs (ADNOC and CNOOC) as well as agreements in security, nuclear energy, and real estate.^[ "UAE, China sign 16 agreements to boost ties in energy, investment", *Gulf Business*, https://gulfbusiness.com/uae-china-sign-16-agreements-to-boost-ties-in-energy-investment/.] NOC ties are a critical component of deepening bilateral links between China and the UAE. 

The political salience of trade ties is well established in political economy, and there are robust literatures addressing the causes and consequences of variation in trade.^[ **Insert Trade Cites**.] Directly engaging with these literatures is out of scope for this chapter. 
### NOC internationalization and the international system

Third, the political implications of NOC activity abroad are likely not limited to bilateral diplomatic or trade effects; they may also play a role in how a state interacts with, is percieved by, or signals to the international community broadly speaking. When the actions of the state and the actions of the firm are difficult to distinguish, either by virtue of the substance of the action or the roles and responsibilities of the actor, then firm activity is more likely to be taken as state activity and reveal information to other states as such. 

One prominent example of this pheonomenon is the role of CNOOC, CNPC, and Sinopec in China's Belt and Road Initiative. The international activity these firms engage in are motivated in large part by commercial aims, but are woven into the fabric of a larger geopolitical and economic strategy for engagement. Firm activity in this context communicates useful information about how China is engaging the world. Critically, this communication isn't restricted to the partners, like the UAE above, that sign bilateral agreements or MOUs: each element of the initiative also sends meaningful signals to the rest of the world, potential partners and rivals alike. 

NOCs can be one of the most significant public-facing institutions of state. Especially when there is a close equivalency between the state and the firm, their actions can convey (or, critically, be taken to convey whether that is the intention of the state or not) valuable information about what the state's priorities are vis-a-vis its external environment. 

### Observable implications and strategies for investigation

Untangling these processes using cross-sectional data --- that is, causally identifying the effect of NOC internationalization on bilateral political, trade, or signalling outcomes --- presents significant challenges. If we accept that some form of these mechanisms likely adhere in some cases (if not in all), we can refocus our attention away from causal identification and instead investigate the cross-sectional patterns that are consistent with their operation. These cross-sectional patterns may not allow us to determine whether NOC activity causes political outcomes or an interest in delivering political outcomes cause NOC activity, but in reality it is likely a mix of both. 

If bilateral political and trade ties matter in the context of NOC internationalization, we should expect to see that these relationships covary with the NOC network. States that have strong links on the trade and diplomatic fronts should have higher NOC-subsidiary links, all else equal. 

> **H1a**: NOC-subsidiary ties are positively correlated with the strength of bilateral diplomatic ties, all else equal.

> **H1b**: States with a NOC-subsidiary connection will have stronger diplomatic ties than states without, all else equal.

> **H2a**: NOC-subsidiary ties are positively correlated with the strength of bilateral trade ties, all else equal.

> **H2b**: States with a NOC-subsidiary connection will have stronger trade ties than states without, all else equal.

If the international activity engaged in by NOCs matters in the context of international signalling, we should expect to see NOC activity mirror that signalling intent. States that are motivated by a desire to integrate into a western-led international order will have firms that invest more extensively in western subsidiaries. Alternatively, states consistently outside of that order will have firms that reflect that separation in their investment targets.

> **H3a**: Rapid westernization / integration will be correlated with greater NOC investment in western subsidiaries, all else equal

> **H3b**: NOC subsidiaries are located in politically similar states, all else equal

Identifying the causal impact of NOC internationalization on political outcomes requires a temporal view rather than (or in addition to) a cross-sectional one. One way of estimating the effect of an intervention such as international NOC activity is by tracking how political outcomes change over time in response to that intervention. Within this set up, we are able to clarify the theoretical propositions given above into testable hypotheses given below:

> **H4a**: NOC internationalization at time *t* leads to improved diplomatic ties in subsequent periods (*t+1 to t+n*)

> **H4b**: NOC internationalization at time *t* leads to improved trade ties in subsequent periods (*t+1 to t+n*)

> **H4c**: NOC internationalization at time *t* leads to improved international integration in subsequent periods (*t+1 to t+n*)