--- 
title: "National Oil Companies as International Investors"
author: "David Tingle"
date: "Last Edited: `r Sys.Date()`"
site: bookdown::bookdown_site
output:
  bookdown::gitbook:
    self_contained: false
documentclass: book
bibliography: support/zotero_library.bib
csl: support/chicago_authordate.csl
link-citations: yes
geometry: margin=1.5in
fontsize: 11pt
always_allow_html: yes
tof: true
description: "A dissertation at the intersection of political economy and business studies."
---

# Overview {-}

National Oil Companies (NOCs) were initially built to give states some degree of control over their domestic hydrocarbon resources, but many of them have now acquired assets and established subsidiaries outside of their home state. This dissertation adresses three key questions related to this phenomenon:

- **First, how does NOC internationalization vary?** NOCs are some of the largest economic entities in existence today. Their international activities often receive high levels of publicity and scrutiny. When Saudi Arabia's Aramco acquires an asset outside of the Kingdom, the Crown Prince is often involved in the announcement and firm executives are accompanied by the highest levels of the diplomatic corps. Despite this significance, however, we don't have a broad or systematic understanding of these international activities. For example, we don't currently know much about which firms have a large international presence and which are limited to domestic operations, which countries are the most common investment targets, whether firms invest in raw resource assets or downstream value chain assets, and so on. The goal of this chapter is to introduce and then utilize an approach to measuring internationalization based on the subsidiaries NOCs establish outside their home state.
- **Second, why are some NOCs highly internationalized and others aren't?** This question is at the core of the current literature on NOC internationalization, but good answers to it are limited by a relatively sparse data environment and by a lack of attention to comprehensive theory development. This chapter addresses the question head on by using graphical causal modelling to develop and then evaluate a theory of NOC internationalization that unifies and builds on exisitng work on the subject.
- **Third, what are the political consequences of NOC internationalization?** The suggestion that NOC activities -- whether they be domestic or international -- can be tied up in politics in meaningful ways is likely uncontroversial. Systematically investigating the political implications of this activity, however, is more challenging. This chapter makes two moves to improve our understanding of this important but under-researched topic. First, it takes a structured approach to definining the range and shape of what these political implications could be, and explores the NOC internationalization data to determine whether patterns in NOC subsidiary networks are consistent with these expectations. Second, it utilizes state-space structural models to investigate the causal impact of internationalization over time on key political outcomes of interest. 

In addressing these questions together as part of a unified project, this research sheds light on a set of integral but under-theorized institutions, NOCs, at the centre of contemporary state capitalism and the political economy of resource wealth.

<br><br>

```{r, fig.height = 4, fig.width = 8, dpi=200, fig.align= 'center', echo=F,message=F,warning=F,cache=T, eval=F}

library(tidyverse)
load("data/out/etl_results.RData")

subsidiary_dataset_FINAL %>%
  filter(Status == "international" & Type == "NOC") %>%
  select(shortname, country, subsidiary_country,
         lat, lon, lat.y, lon.y) %>%
  group_by(shortname, subsidiary_country) %>% 
  summarize(n_subs = n(),
            lat = max(lat),
            lon = max(lon),
            lat.y = max(lat.y),
            lon.y = max(lon.y)) %>% 
  arrange(-n_subs) %>%
  group_by(shortname) %>%
  mutate(tot_n = sum(n_subs)) %>% 
  filter(shortname %in% c("Statoil",  "Petronas", "Sonangol",
                          "Petrobras", "OOC", "Gazprom",
                          "Saudi Aramco", "Eni", "SOCAR")) %>%
  na.omit() %>% 
  ggplot() +
  borders("world", colour = "white", fill = "seashell2") +
  theme_void() +
  coord_cartesian(ylim = c(-50, 80)) +
  geom_curve(aes(x = lon, y = lat,
                 xend = lon.y, yend = lat.y,
                 color = n_subs),
             curvature = .0) +
  geom_point(aes(lon.y, lat.y, color = n_subs)) +
  geom_point(aes(lon, lat)) +
  facet_wrap(~shortname) +
  scale_color_continuous(low = "grey70", high = "tomato") +
  theme(legend.position="none",
        legend.title = element_blank())
```



